### ISSUE TITLE
w/series-9/about/dev: Вид на мобильном в ландшафтном режиме не по макету

### ISSUE THREAD

**Issue by bronley** [webliumteam/blocks#3555]
Телефон и планшет должны находиться на одном уровне по макету.
В ландшафтном режиме телефон и планшет по разные стороны экрана
https://jmp.sh/9rzaq5w

**Comment by t-nick** [comment]
на app уже по макету, сейчас блок еще правиться https://github.com/webliumteam/blocks/pull/3859

**Comment by mputilov** [comment]
pr #3859 закрыт, пофикшено
