### ISSUE TITLE
w/series-9/about/dev: Белая полоска на iPad 

### ISSUE THREAD

**Issue by bronley** [webliumteam/blocks#3560]
Белая полоска на iPad сверху с включенным планшетом и телефоном Swap Right
https://jmp.sh/YEJXtXC

**Comment by t-nick** [comment]
На app сейчас не воспроизводится.  скорее всего решиться после мержда на прод . тикет https://github.com/webliumteam/blocks/pull/3859

**Comment by michailozdemir** [comment]
https://github.com/webliumteam/blocks/pull/3896
