### ISSUE TITLE
wireframe-series-2-contacts горизонтальная прокрутка

### ISSUE THREAD

**Issue by artemvasilkin** [webliumteam/blocks#3562]
@michailozdemir , В блоке wireframe-series-2-contacts нужно исправить `margin: -30px;` (скорее всего просто заменить на `-15px`

Репортер: **Vlad Husiev**
Пример сайта: https://54egl.weblium.site/
Скрин: https://jmp.sh/OT2DSZM

**Comment by michailozdemir** [comment]
Fixed @artemvasilkin 
Нужен репаблиш на прод.

https://github.com/webliumteam/blocks/issues/3563

**Comment by michailozdemir** [comment]
Уже был смерджен. 
https://github.com/webliumteam/blocks/pull/3563
