### ISSUE TITLE
Чистка блоков от type: primary

### ISSUE THREAD

**Issue by artemvasilkin** [webliumteam/blocks#3886]
### Список блоков

w/series-1/cover/dev
w/series-1/elements_table/dev
w/series-1/extra_cookies/dev
w/series-1/gallery/dev
w/series-1/header/dev
w/series-1/other_cover/dev
w/series-1/other_stub/dev
w/series-1/projects/dev
w/series-10/cta/dev
w/series-10/services/dev
w/series-10/team/dev
w/series-11/about/dev
w/series-11/contacts/dev
w/series-11/cover/dev
w/series-11/header/dev
w/series-11/partners/dev
w/series-12/cta/dev
w/series-12/features/dev
w/series-12/partners/dev
w/series-12/process/dev
w/series-12/services/dev
w/series-13/header/dev
w/series-14/cta/dev
w/series-14/header/dev
w/series-14/services/dev
w/series-15/services/dev
w/series-16/header/dev
w/series-16/team/dev
w/series-17/header/dev
w/series-2/about/dev
w/series-2/blog/dev
w/series-2/careers/dev
w/series-2/contacts/dev
w/series-2/countdown/dev
w/series-2/cover/dev
w/series-2/cta/dev
w/series-2/gallery/dev
w/series-2/other_cover/dev
w/series-3/cover/dev
w/series-3/cta/dev
w/series-3/footer/dev
w/series-3/numbers/dev
w/series-4/blog/dev
w/series-4/contacts/dev
w/series-4/description/dev
w/series-4/gallery/dev
w/series-4/menu/dev
w/series-5/careers/dev
w/series-5/cta/dev
w/series-5/events/dev
w/series-5/gallery/dev
w/series-5/numbers/dev
w/series-5/pricing/dev
w/series-5/schedule/dev
w/series-6/careers/dev
w/series-6/cover/dev
w/series-6/footer/dev
w/series-6/header/dev
w/series-6/partners/dev
w/series-6/projects/dev
w/series-6/testimonials/dev
w/series-7/contacts/dev
w/series-7/header/dev
w/series-7/numbers/dev
w/series-7/partners/dev
w/series-7/process/dev
w/series-7/schedule/dev
w/series-8/awards/dev
w/series-8/contacts/dev
w/series-8/gallery/dev
w/series-8/schedule/dev
w/series-8/timeline/dev
w/series-9/careers/dev
w/series-9/header/dev
w/series-9/projects/dev
w/series-9/services/dev
w/series-9/team/dev
w/series-9/testimonials/dev

**Comment by artemvasilkin** [comment]
@t-nick

**Comment by t-nick** [comment]
сделала
