### ISSUE TITLE
Чистка блоков от console.log()

### ISSUE THREAD

**Issue by artemvasilkin** [webliumteam/blocks#3888]
### Список блоков

- [x] w/series-13/features/dev
- [x] w/series-2/other_cover/dev
- [x] w/series-6/blog/dev
- [ ] w/series-9/gallery/dev

**Comment by nmelnychenko** [comment]
w/series-6/blog/dev - обернул в if ($editor.mode === 'editor')
w/series-9/gallery/dev - @t-nick
