### ISSUE TITLE
Блок wireframe-series-10-cta с длинным текстом паддинг считается не от края блока

### ISSUE THREAD

**Issue by artemvasilkin** [webliumteam/blocks#3898]
Скрин
![luwt7zpvcda_xvrc0m6yx9qbni7brwhg2f3ogxzvwegkzbche_rwmhazx_dmkbqofqypwppbykek8ca_zvvwjlnlsmh0egfbdyhze6lvomai4av1wcwksmudutgzhrrg](https://user-images.githubusercontent.com/25356465/46143164-d40c6b00-c261-11e8-892a-f147b6be10b0.gif)

**Comment by mputilov** [comment]
пофикшено
