### ISSUE TITLE
w/series-6/contacts/dev: Проблемы со шрифтами в белой плашке

### ISSUE THREAD

**Issue by bronley** [webliumteam/blocks#3921]
В эдиторе при выключении "Wroking hours" или "Location heading", шрифты в белой плашке в айтеме начинают вести себя странно при наведении на плашку курсором.
На паблише всё ок.
https://jmp.sh/OeqndUW

**Comment by nmelnychenko** [comment]
https://github.com/webliumteam/blocks/pull/3955

**Comment by nmelnychenko** [comment]
Размытый шрифт нет возможности исправить, а "дергание" - убрал.
