### ISSUE TITLE
Добавить roles в package.json для header, footer и cover 

### ISSUE THREAD

**Issue by artemvasilkin** [webliumteam/blocks#3923]
Hет роли в таких header:
      'w/series-10/header/dev',
      'w/series-11/header/dev',
      'w/series-13/header/dev',
      'w/series-14/header/dev',
      'w/series-16/header/dev',
      'w/series-5/header/dev',
      'w/series-6/header/dev',
      'w/series-7/header/dev',
      'w/series-8/header/dev',
      'w/series-9/header/dev',

Нет роли в таких footer:
      'w/series-4/footer/dev',
      'w/series-5/footer/dev',
      'w/series-6/footer/dev',

Нет роли в таких cover:
  w/series-10/cover/dev
  w/series-11/cover/dev
  w/series-14/cover/dev
  w/series-5/cover/dev
  w/series-6/cover/dev
  w/series-9/cover/dev

**Comment by t-nick** [comment]
сделала
