### ISSUE TITLE
Новые модификации компонент w-section и typography

### ISSUE THREAD

**Issue by artemvasilkin** [webliumteam/blocks#5203]
У нас новые БЕМ-модификаторы в компонентах `w-section` и в типографике.

1. Теперь, если `w-section__header` или `w-section__footer` составляет ~50% от ширины блока (как в `series-1/about`), мы добавляем этим элементам дополнительный класс `w-section__header--50` или `w-section__footer--50`

2. Если `w-subtitle|heading|heading-lg|subheading` составляет 50|33|25|20% от ширины блока (например, в коллекциях), мы добавляем этим элементам дополнительный класс `w-subtitle|heading|heading-lg|subheading--50|33|25|20`

- [x] 1. wireframe-series-2-header
- [x] 2. wireframe-series-3-footer
- [x] 3. wireframe-series-1-cover
- [x] 4. wireframe-series-3-gallery
- [x] 5. wireframe-series-6-cta
- [x] 6. wireframe-series-2-cover
- [x] 7. wireframe-series-1-about
- [x] 8. wireframe-series-1-careers
- [x] 9. wireframe-series-10-projects
- [x] 10. wireframe-series-11-contacts
- [x] 11. wireframe-series-2-cta
- [x] 12. wireframe-series-2-services
- [x] 13. wireframe-series-3-about
- [x] 14. wireframe-series-4-team
- [x] 15. wireframe-series-5-gallery
- [x] 16. wireframe-series-7-contacts
- [x] 17. wireframe-series-7-gallery
- [x] 18. wireframe-series-9-careers
- [x] 19. wireframe-series-1-about
- [x] 20. wireframe-series-1-awards
- [x] 21. wireframe-series-1-contacts
- [x] 22. wireframe-series-1-projects
- [x] 23. wireframe-series-1-services
- [x] 24. wireframe-series-1-testimonials

**Comment by t-nick** [comment]
wireframe-series-1-testimonials  не нужно

**Comment by artemvasilkin** [comment]
@mputilov , https://docs.google.com/spreadsheets/d/1m5wIKzkoWNd5uj0bjKeOsIkXfyNN3yK-1_3mZLSEKzY/edit?usp=sharing
