### ISSUE TITLE
Вводим w-picture-wrapper--hero & --person

### ISSUE THREAD

**Issue by artemvasilkin** [webliumteam/blocks#5473]
### Hero

- [x] 1. w/series-1/about/dev
- [x] 2. w/series-10/about/dev
- [x] 3. w/series-11/about/dev
- [x] 4. w/series-3/about/dev
- [x] 5. w/series-7/about/dev
- [x] 6. w/series-10/blog/dev
- [x] 7. w/series-6/blog/dev
- [x] 8. w/series-1/careers/dev
- [x] 9. w/series-3/careers/dev
- [x] 10. w/series-5/careers/dev
- [x] 11. w/series-7/careers/dev
- [x] 12. w/series-14/features/dev
- [x] 13. w/series-10/cover/dev
- [x] 14. w/series-19/cover/dev
- [ ] 15. w/series-6/gallery/dev
- [x] 16. w/series-7/gallery/dev
- [x] 17. w/series-1/other_about/dev
- [x] 18. w/series-14/process/dev
- [x] 19. w/series-9/process/dev
- [x] 20. w/series-15/services/dev
- [ ] 21. w/series-2/team/dev
- [x] 22. w/series-8/team/dev
- [x] 23. w/series-9/team/dev
- [x] 24. w/series-6/testimonials/dev

### Person

- [ ] 1. w/series-13/blog/dev
- [ ] 2. w/series-2/blog/dev
- [x] 3. w/series-6/blog/dev
- [x] 4. w/series-1/other_about/dev
- [x] 5. w/series-4/schedule/dev
- [x] 6. w/series-5/schedule/dev
- [x] 7. w/series-15/services/dev
- [x] 8. w/series-1/team/dev
- [x] 9. w/series-10/team/dev
- [x] 10. w/series-11/team/dev
- [x] 11. w/series-16/team/dev
- [ ] 12. w/series-2/team/dev
- [x] 13. w/series-6/team/dev
- [x] 14. w/series-7/team/dev
- [x] 15. w/series-1/testimonials/dev
- [ ] 16. w/series-18/testimonials/dev
- [x] 17. w/series-9/testimonials/dev

**Comment by mputilov** [comment]
13/blog - нет на проде
2/blog - очень маленькие кружочки
2/team - нет на проде
18/testimonials - нет на проде
