### ISSUE TITLE
w-icon--symbol добавить новую сущность

### ISSUE THREAD

**Issue by t-nick** [webliumteam/blocks#5546]
нужно добавить новую сущность w-icon-small в блоки где ее можно применить. Эти иконки, которе не несут смысла (чекбоксы, значки) пример блоков:

- [x] 1. 11/services
- [ ] 2. 5/pricing
- [x] 3. 1/menu
- [x] 4. 8/features
- [x] 5. 4/description
- [x] 6. 8, 10 - 13/careers

**Comment by nmelnychenko** [comment]
5/pricing - нет иконок
