### ISSUE TITLE
w-card__heading

### ISSUE THREAD

**Issue by t-nick** [webliumteam/blocks#5653]
Для декорирования heading только в коллекциях нужно добавить класс w-card__heading  к хедингам карточек , например https://jmp.sh/0ymi4SD

**Comment by nmelnychenko** [comment]
Блоки с 'w-card'
- [ ] w/series-1/awards/dev
- [ ] w/series-1/blog/dev
- [ ] w/series-1/features/dev
- [ ] w/series-1/gallery/dev
- [ ] w/series-1/numbers/dev
- [ ] w/series-1/process/dev
- [ ] w/series-1/services/dev
- [ ] w/series-1/team/dev
- [ ] w/series-10/careers/dev
- [ ] w/series-10/features/dev
- [ ] w/series-10/team/dev
- [ ] w/series-11/projects/dev
- [ ] w/series-12/features/dev
- [ ] w/series-12/services/dev
- [ ] w/series-14/team/dev
- [ ] w/series-16/projects/dev
- [ ] w/series-16/services/dev
- [ ] w/series-16/team/dev
- [ ] w/series-2/awards/dev
- [ ] w/series-2/blog/dev
- [ ] w/series-2/contacts/dev
- [ ] w/series-2/description/dev
- [ ] w/series-2/features/dev
- [ ] w/series-2/partners/dev
- [ ] w/series-2/pricing/dev
- [ ] w/series-2/schedule/dev
- [ ] w/series-2/testimonials/dev
- [ ] w/series-23/services/dev
- [ ] w/series-3/features/dev
- [ ] w/series-3/numbers/dev
- [ ] w/series-4/faq/dev
- [ ] w/series-4/gallery/dev
- [ ] w/series-4/menu/dev
- [ ] w/series-4/schedule/dev
- [ ] w/series-5/cover/dev
- [ ] w/series-5/numbers/dev
- [ ] w/series-6/partners/dev
- [ ] w/series-6/projects/dev
- [ ] w/series-7/awards/dev
- [ ] w/series-7/partners/dev
- [ ] w/series-7/process/dev
- [ ] w/series-8/awards/dev
- [ ] w/series-8/blog/dev
- [ ] w/series-8/contacts/dev
- [ ] w/series-8/features/dev
- [ ] w/series-8/pricing/dev
- [ ] w/series-8/schedule/dev
- [ ] w/series-8/services/dev
- [ ] w/series-9/features/dev
- [ ] w/series-9/partners/dev
- [ ] w/series-9/services/dev
- [ ] w/series-9/testimonials/dev
